apiVersion: batch/v1
kind: Job
metadata:
  name: ba-data-process-job
spec:
  completions: 1
  template:
    metadata:
      labels:
        app: ba-party-analyze
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: ba-data-process
          image: ghcr.io/beaverhouse/ba-data-process:v0.1.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: ba-party-analyze-secret
          env:
            - name: GO_ENV
              value: "production"
