apiVersion: batch/v1
kind: CronJob
metadata:
  name: ba-party-analyze-job
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      completions: 1
      template:
        metadata:
          labels:
            app: ba-party-analyze
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: ghcr-secret
          containers:
            - name: ba-party-analyzer
              image: ghcr.io/beaverhouse/tinyclover-ba-party-analyzer:v0.1.9
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: ba-worker-secret
              env:
                - name: GO_ENV
                  value: "production"
