apiVersion: batch/v1
kind: CronJob
metadata:
  name: ba-party-discovery-cronjob
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: ba-party-discovery
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: ghcr-secret
          containers:
            - name: ba-party-discovery
              image: ghcr.io/beaverhouse/tinyclover-ba-autodiscovery:v0.1.6
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: ba-worker-secret
              env:
                - name: GO_ENV
                  value: "production"
                - name: CONTENT_ID
                  value: "3S29-1"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ba-party-discovery-cronjob
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: ba-party-discovery
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: ghcr-secret
          containers:
            - name: ba-party-discovery
              image: ghcr.io/beaverhouse/tinyclover-ba-autodiscovery:v0.1.6
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: ba-worker-secret
              env:
                - name: GO_ENV
                  value: "production"
                - name: CONTENT_ID
                  value: "3S29-2"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ba-party-discovery-cronjob
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: ba-party-discovery
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: ghcr-secret
          containers:
            - name: ba-party-discovery
              image: ghcr.io/beaverhouse/tinyclover-ba-autodiscovery:v0.1.6
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: ba-worker-secret
              env:
                - name: GO_ENV
                  value: "production"
                - name: CONTENT_ID
                  value: "3S29-3"
