apiVersion: batch/v1
kind: Job
metadata:
  name: ba-party-analyze-job
spec:
  completions: 1
  template:
    metadata:
      labels:
        app: ba-party-analyze
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: ba-party-analyzer
          image: ghcr.io/beaverhouse/tinyclover-ba-party-analyzer:v0.1.4
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: ba-worker-secret
          env:
            - name: GO_ENV
              value: "production"
