apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ba-worker-external-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gitlab-clustersecretstore
    kind: ClusterSecretStore
  target:
    name: ba-worker-secret
    creationPolicy: Owner
  data:
    - secretKey: "POSTGRES_HOST"
      remoteRef:
        key: "SUPABASE_POSTGRES_HOST"
    - secretKey: "POSTGRES_USER"
      remoteRef:
        key: "SUPABASE_POSTGRES_USER"
    - secretKey: "POSTGRES_PASSWORD"
      remoteRef:
        key: "SUPABASE_POSTGRES_PASSWORD"
    - secretKey: "GEMINI_API_KEY"
      remoteRef:
        key: "GEMINI_FREE_API_KEY"
    - secretKey: "YOUTUBE_API_KEY"
      remoteRef:
        key: "YOUTUBE_API_KEY"
    - secretKey: "BATORMENT_DUCKDB_REMOTE_URL"
      remoteRef:
        key: "BATORMENT_DUCKDB_REMOTE_URL"
    - secretKey: "FILE_MANAGER_SERVICE_API_KEY"
      remoteRef:
        key: "FILE_MANAGER_SERVICE_API_KEY"
