{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-chimgu-routes
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: chimgu
  to:
    - group: gateway.networking.k8s.io
      kind: Gateway
{{- end }}
